Migrate Asn1EncodedDataRouter to use Spring Kafka
CDOT-CV/jpo-ode pull request #138
Opened 2024-12-24 21:13 UTC by mcook42

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-12-27 00:38 UTC, mcook42 reviewed
I would recommend reviewing the Asn1EncodedDataRouter code from within your IDE. There are a lot of changes in there that don't necessarily work well with GitHub's viewer. The processing flow should not have changed. The changes in that file should be in one of four categories:

1. Deduplication of JSON processing
2. Deduplication of message signing or encoding
3. Using the SerializationConfig-provided Object Mapper instead of JsonUtils or TimTransmorgrifier or other JSON serdes (there were a few weird ones).
4. Extracting logic into named methods to reduce cognitive complexity

2024-12-27 00:38 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    } catch (Exception e) {
Note: this is one of the rare times in this code where we can safely continue (as far as I can tell from the code) processing a message should an Exception be thrown. I intentionally handled the expectation here and allowed the processing to continue. I couldn't find any downstream issues in the code. Also, please note that we already handled the exception and continued processing in the previous implementation. This does not change the code flow.

2024-12-27 00:38 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    }
Note: this is one of the rare times in this code where we can safely continue (as far as I can tell from the code) processing a message should an Exception be thrown. I intentionally handled the expectation here and allowed the processing to continue. I couldn't find any downstream issues in the code. Also, please note that we already handled the exception and continued processing in the previous implementation. This does not change the code flow.

2024-12-27 00:38 UTC, mcook42 commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/OdeTimJsonTopologyTest.java
Note: This code is heavily tested indirectly by the Asn1EncodedDataRouter tests. The existing tests were not adding much value (I wrote most of them, so my bad), and meaningful tests were difficult to write without duplicating much of the testing already performed in the Asn1EncodedDataRouter tests.

2025-01-14 23:48 UTC, dmccoystephenson requested changes

2025-01-14 23:48 UTC, dmccoystephenson commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/rsu/RsuDepositorConfig.java
> +   *                               used to determine if RSU signing is enabled.
Suggestion (non-blocking): The current description for this parameter might be somewhat misleading. I think the referenced configuration option controls whether the ODE initiates the signing process for messages intended for RSUs. Typically, if this option is set to false, it indicates that the RSU is expected to handle message signing, and double-signing should be avoided.

Updating the parameter description to something like the following would help improve clarity:
```suggestion
   * @param securityServicesProps the configuration properties for security services,
   *                               used to determine whether the ODE should send the message 
   *                               to be signed prior to sending it to the RSU.```

2025-01-15 15:18 UTC, mcook42 commented on docker-compose.yml
> +    build: ./jpo-security-svcs/ext-signature-svc-mock/
ah, good catch. updated https://github.com/CDOT-CV/jpo-ode/pull/138/commits/f3d1cc416fe4ec35d16c608da44caa7424b3cbe6

2025-01-15 15:18 UTC, mcook42 commented on docker-compose.yml
> +    build: ./jpo-security-svcs/security-svc
good catch. updated https://github.com/CDOT-CV/jpo-ode/pull/138/commits/f3d1cc416fe4ec35d16c608da44caa7424b3cbe6

2025-01-28 16:56 UTC, dmccoystephenson requested changes

2025-01-28 16:56 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processSignedMessage() throws IOException {
Suggestion (non-blocking): Could we rename this test to clarify that we are processing an unsigned message that we intend to sign?

2025-01-28 16:56 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processEncodedTimUnsigned() throws IOException {
Suggestion (non-blocking): Is this test for the case where we have already encoded the message once? If so, is there any way to rename this test to make that clearer?

2025-01-28 16:56 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
Question (non-blocking): I notice that we have tests for signing a TIM meant for the SDX, not signing a TIM meant for the SDX and processing an unsigned already-encoded message meant for the SDX. Should we have any unit tests for the following cases?
- Signing a TIM meant for RSUs
- Not signing a TIM meant for RSUs
- Processing a signed already-encoded message meant for the SDX

2025-01-31 17:03 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/snmp/SnmpSession.java
> +   * @param pdu The message content to be sent to the target
good catch. I think this makes more sense https://github.com/CDOT-CV/jpo-ode/pull/138/commits/8762b518d6c3b0d55ae8f85bc7a83ccc846d055d

2025-01-31 17:05 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/snmp/SnmpSession.java
> +   * @param dataSigningEnabledRSU A boolean flag indicating if data signing is enabled for the RSU.
updated https://github.com/CDOT-CV/jpo-ode/pull/138/commits/eeb3450f9b8e44b7ef32a4e7124c693b3a981844

2025-01-31 17:06 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/snmp/SnmpSession.java
> +   *                              RSU.
updated https://github.com/CDOT-CV/jpo-ode/pull/138/commits/bb176ff1f199dfa6cfdacaa0ae033424b805b149

2025-01-31 17:39 UTC, mcook42 commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processUnsignedMessage() throws IOException {
I had to re-read and step through this test with a debugger to see what you're saying. When stepping through with a debugger, I see that we _are_ signing this message.

2025-01-31 17:41 UTC, mcook42 commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processEncodedTimUnsigned() throws IOException {
i've updated method names and their tests to improve clarity. let me know what you think https://github.com/CDOT-CV/jpo-ode/pull/138/commits/8575184bba16871e221719d21ee3968d29204857

2025-01-31 17:41 UTC, mcook42 commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processSignedMessage() throws IOException {
i've updated method names and their tests to improve clarity. let me know what you think https://github.com/CDOT-CV/jpo-ode/commit/8575184bba16871e221719d21ee3968d29204857

2025-01-31 17:41 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
>      // strip everything before 001F
I've made some updates to this. let me know if this answers your question or if you have any suggestions https://github.com/CDOT-CV/jpo-ode/pull/138/commits/9eca32bfc4d652a12ce11004cb0d1325af99d5b3

2025-01-31 17:42 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +          "ASN.1 decoding failed with code %s and message %s.".formatted(code, message));
addressed https://github.com/CDOT-CV/jpo-ode/pull/138/commits/e702fa30715f9435d1ad269b7662c92fdd72dff5

2025-01-31 18:16 UTC, mcook42 commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
That's a really good question. I reviewed the code flows to see if there was much value to these missing test cases. Here are my thoughts:

>Signing a TIM meant for RSUs

This one may or may not be useful. There is only one difference I can see between this flow and the others already under test. That difference is the call to [rsuDepositor.deposit](https://github.com/CDOT-CV/jpo-ode/blob/8575184bba16871e221719d21ee3968d29204857/jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java#L367). Since the deposit method is already covered by the [testDeposit](https://github.com/CDOT-CV/jpo-ode/blob/3e414a13cad3c0e4f51f0d89cd96b8d18f811570/jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/rsu/RsuDepositorTest.java#L43) method, I'm not sure it's worth the effort and test execution time to implement as an integration test. There may be some value to adding it as a heavily-mocked unit test, but I'm on the fence about that effort.

>Not signing a TIM meant for RSUs

I don't see enough value in this test case to warrant adding another Integration test case to cover this flow. The only difference between this flow and the "signing a TIM meant for RSUs" case is that we do not send the message for signing. This means _all other code in this flow is already tested_, and the new test case would only confirm that we set `bytesToSend = hexEncodedTimBytes` instead of the singed bytes (the other test already confirms the if-else check functions). If this were a quick, fast, and easy unit test, I would say yes, but this is an expensive, somewhat slow integration test, so I don't think it's worth adding a test case.

>Processing a signed already-encoded message meant for the SDX

This should already be covered in the test (now named) `processDoubleEncodedMessage`


Please let me know your thoughts!

2025-02-03 21:06 UTC, dmccoystephenson commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
>      // strip everything before 001F
Looks good!

2025-02-03 21:07 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processSignedMessage() throws IOException {
That looks good, thanks for doing that!

2025-02-03 21:07 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processEncodedTimUnsigned() throws IOException {
I like it!

2025-02-03 21:13 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
> +  void processUnsignedMessage() throws IOException {
Thanks for that clarification, my mistake!

2025-02-03 21:15 UTC, dmccoystephenson commented on jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouterTest.java
I agree with your thoughts—given the existing coverage, I don’t see a strong need to add these additional tests. Since the key differences are already accounted for in other test cases, I don't think the effort and execution time required for new integration tests would provide enough value. No further tests are needed from my perspective.

2025-02-03 21:53 UTC, dmccoystephenson approved these changes
This looks good to me & the unit tests pass! Great job on this refactor!

2025-02-05 14:57 UTC, mwodahl approved these changes
This looks good to me!

2025-02-07 16:23 UTC, Michael7371 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -        EventLogger.logger.error(msg, e);
I also had this question when looking through some of the OBU log processing logic. It seems like certain areas of the ODE code uses the event logger, but I am not sure why.

2025-02-07 16:48 UTC, Michael7371 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -          }
I agree with this code having no functional impact.

2025-02-07 16:48 UTC, Michael7371 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -        EventLogger.logger.error(msg, e);
Maybe that eventlogger was used to allow for more customized logging?

2025-02-10 19:51 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -          }
I think the original intent was to remove the RSUs string from the request if empty to avoid issues, but the actual use seems to have either been remove or not implemented. I agree, seems able to be removed

2025-02-10 19:53 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -        EventLogger.logger.error(msg, e);
Looks to be a static class approach to the logger implementation, as Michael said, likely attempting to control logging across the system. It wasn't fully implemented though, and creates a hodge-podge of logging. I'm fine tanking this for the standard approach

2025-02-10 23:03 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +   * signed Traveler Information Message (TIM). Processes the provided service request and signed
suggestion: the ASD doesn't always have a _signed_ TIM. We should update documentation to reflect it's just a TIM, and ensure our code paths are capable of delivering unsigned

2025-02-10 23:09 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    SNMP snmp = request.getSnmp();
suggestion: We're only packing into ASD if we're depositing into the SDX, so we should ignore the SNMP portion here and just take the SDW.

2025-02-10 23:16 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +  // no SDW in metadata (SNMP deposit only) -> sign MF -> send to RSU
suggestion: this comment is a little misleading, we certainly could have SDW in metadata here and frequently do.

2025-02-10 23:18 UTC, payneBrandon commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    JSONObject deposit = new JSONObject();
question(non-blocking): would it be worth making a POJO for this object that gets sent to the SdwDepositor and on to the SDX?

2025-02-12 18:55 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    JSONObject deposit = new JSONObject();
yeah, it was simple enough to implement so I defined one in https://github.com/CDOT-CV/jpo-ode/pull/138/commits/7c03ccebc68c234179850381cd24507a4e1ffece

2025-02-12 18:56 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +  // no SDW in metadata (SNMP deposit only) -> sign MF -> send to RSU
Good callout. I've removed the comment in favor of "self-documenting" code https://github.com/CDOT-CV/jpo-ode/pull/138/commits/20a7b0a35204d8dfdd7fd200e094d9d2a75e7203

2025-02-12 18:56 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +   * signed Traveler Information Message (TIM). Processes the provided service request and signed
updated the javadoc comment to remove the "signed" portion https://github.com/CDOT-CV/jpo-ode/pull/138/commits/3a07370bb46017e09d5efc0e4f43242daaf666e2

2025-02-12 23:29 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> +    SNMP snmp = request.getSnmp();
updated: https://github.com/CDOT-CV/jpo-ode/pull/138/commits/efd5f3dd7b8c61822784b14c5e640b488cf95311

2025-02-13 15:22 UTC, drewjj requested changes
Everything passes tests and works for the most part. The one thing that seems to no longer be occurring is that TIM messages are not being written to the topic.OdeTimJsonTMCFiltered topic. This seems to occur no matter how you configure the jpo-ode to sign TIMs. This seems incorrect. Am I missing something?

2025-02-13 16:18 UTC, drewjj approved these changes
Re-tested with the security module running and everything is working correctly. My mistake on not running the sec module! Having both RSU and SDW set to unsigned still results in this behavior but this is apparently how the existing functionality works too.

Everything looks to be good to go.

2025-02-19 00:33 UTC, mcook42 commented on jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
> -          }
turns out this was necessary. I put it back but in a little clearer way https://github.com/CDOT-CV/jpo-ode/pull/138/commits/3ddfaa35937f98d12a078c9fce80d4ca6562c57d

2025-02-19 16:27 UTC, Michael7371 approved these changes
Looks really good! I like the updates here. One other question I had is that I had to update the jpo-security-svcs module reference in the `.gitmodules` file. Should this PR modify that reference so it is in line with what the current ODE expects?

Passed Checks:
1. tests pass
2. log files process properly
3. All services start up through docker-compose
4. REST created TIMs for SDW deposit functions properly
5. REST created TIMs for SNMP deposit functions properly

2025-02-20 21:49 UTC, merged