GitHub actions artifact publishing
CDOT-CV/jpo-ode pull request #94
Opened 2024-07-29 19:16 UTC by Michael7371

# PR Details
## Description

Adding maven JAR publishing to GitHub Maven Central.

## Related Issue

## Motivation and Context

To allow for less reliance on Git submodules when needing jpo-ode artifacts

## How Has This Been Tested?

Tested a trigger manually and pulling the generated jar files

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ x ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2024-08-01 20:00 UTC, drewjj approved these changes
Looks good!

2024-08-02 22:00 UTC, dmccoystephenson requested changes

2024-08-02 22:12 UTC, dmccoystephenson approved these changes
Looks good to me!

2024-08-02 22:13 UTC, drewjj approved these changes
Looks good

2024-08-14 17:10 UTC, payneBrandon approved these changes
lgtm!

2024-08-14 17:10 UTC, merged